#-------------------
# Makefile Config.  
#-------------------

MAIN = mwords
LIBS =  -lm `sdl-config --libs` -lSDL_ttf
CFLAGS = -I../../include/

include ../../config/Makefile.cflags
include ../../config/Makefile.in
