#!/bin/bash


if [ "$1" = "--noask" ]; then
	echo "Script launched with --noask. Cleaning without confirmation."
	DO_CLEAN=1;
else
	echo -e 'Are you sure (Yes/no)? \c'
	read USER_CHOICE;
	
	if [ "$USER_CHOICE" == "Yes" ]; then
		echo "User choose to clean.";
		DO_CLEAN=1;
	else
		echo "User choose not to clean.";
		DO_CLEAN=0;
	fi
fi
	
if [ "$DO_CLEAN" == "1" ]; then
	echo -e 'Waiting 10 seconds: \c';
	for x in `seq 0 9`; do
		echo -e "$((9 - $x)) \a\c";
		sleep 1;
	done
	echo "Cleaning!";

	# If the experiment folder has been created
	# using the repo/exp_* archive, clean dummy 
	# files.
	for dummy in `find . -iname "dummy.txt"`; do
		rm -v $dummy;
	done

	# If you are almost ready for a (long) coffee 
	# break, nuke everything in the cache folder:
	#rm -v cache/*
	# If you are on hurry, keep the *_track.wav files:
	for entry in `find cache/ | grep -v "track.wav"`; do
		rm -v $entry;
	done

	# Log and Tmp files could stay where they are, but performing
	# some cleaning is a good idea
	rm -v log/*
	rm -v temp/*

	# Cleaning the SEQ folders is NECESSARY and cannot
	# be avoided.
	for folder in `find . -iname "seq_*"`; do
		rm -v $folder/*;
	done
fi
