#!/bin/bash
# LTC_S0
# lmtools2 toolchain: step 0
# Cleans lmtools2 experiment folder

for dummy in `find . -iname "dummy.txt"`; do
	rm -v $dummy;
done

rm -v cache/*
rm -v log/*
rm -v temp/*

for folder in `find . -iname "seq_*"`; do
	rm -v $folder/*;
done
