#!/bin/bash
# Copyright (C) 2007 Michele Tavella <michele@liralab.it>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

echo -e '[lm_cleanmat] Waiting 10 seconds: \c';
for x in `seq 0 9`; do
	echo -e "$((9 - $x)) \a\c";
	sleep 1;
done;

echo "[lm_cleanmat] Looking for .mat files"
for i in `find seq* | grep .mat `; do rm -v $i; done
for i in `find dist* | grep .mat `; do rm -v $i; done
echo "[lm_cleanmat] Looking for .txt files"
for i in `find seq* | grep .txt `; do rm -v $i; done
for i in `find dist* | grep .txt `; do rm -v $i; done
