#!/bin/bash
# Copyright (C) 2007 Michele Tavella <michele@liralab.it>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

if [ "$1" = "--noask" ]; then
	echo "Script launched with --noask. Cleaning without confirmation."
	DO_CLEAN=1;
else
	echo -e 'Are you sure (Yes/no)? \c'
	read USER_CHOICE;
	
	if [ "$USER_CHOICE" == "Yes" ]; then
		echo "User choose to clean.";
		DO_CLEAN=1;
	else
		echo "User choose not to clean.";
		DO_CLEAN=0;
	fi
fi
	
if [ "$DO_CLEAN" == "1" ]; then
	echo -e 'Waiting 10 seconds: \c';
	for x in `seq 0 9`; do
		echo -e "$((9 - $x)) \a\c";
		sleep 1;
	done
	echo "Cleaning!";

	rm -fv temp/*
fi
