#!/usr/bin/perl

my $folder = 0;
if ($#ARGV>=0) {
    $folder = $ARGV[0];
}

my @audio_files_ns = `find $folder/ -iname "*cc.wav"`;
my @audio_files = sort {$a cmp $b} @audio_files_ns;


foreach $file_cc (@audio_files) {
	chomp($file_cc);
#	print "$file\n";

	my $file_wd = $file_cc;
	$file_wd =~ s/_cc.wav/.wav/g;
	my $file_ag = $file_cc;
	$file_ag =~ s/_cc.wav/_ag.wav/g;
	
	system("clear");
	print "-------------------------------------\n";
	print "WD file $file_wd\n";
	print "AG file $file_ag\n";
	print "CC file $file_cc\n";
	print "-------------------------------------\n";
	system("play $file_wd");
	system("play $file_ag");
	system("play $file_cc");
	#system("sleep 0.5");
}
