#!/usr/bin/perl
# Copyright (C) 2007 Michele Tavella <michele@liralab.it>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

my $folder = 0;
if ($#ARGV>=0) {
    $folder = $ARGV[0];
}

my @audio_files_ns = `find $folder/ -iname "*cc.wav"`;
my @audio_files = sort {$a cmp $b} @audio_files_ns;


foreach $file_cc (@audio_files) {
	chomp($file_cc);
#	print "$file\n";

	my $file_wd = $file_cc;
	$file_wd =~ s/_cc.wav/_us.wav/g;
	my $file_ag = $file_cc;
	$file_ag =~ s/_cc.wav/_ag.wav/g;
	
	system("clear");
	print "-------------------------------------\n";
	print "WD file $file_wd\n";
	print "AG file $file_ag\n";
	print "CC file $file_cc\n";
	print "-------------------------------------\n";
	system("play $file_wd");
	system("play $file_ag");
	system("play $file_cc");
	#system("sleep 0.5");
}
