#!/usr/bin/perl
# Copyright (C) 2007 Michele Tavella <michele@liralab.it>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

use Getopt::Long;
use File::Copy;
use Cwd;
use Term::ANSIColor;
use Sys::Hostname;
use POSIX qw(ceil floor);
use strict;

my $data_type = shift;
my $file_type = "";			# AMP or POS?
my $cmd_stdo  = "1>/dev/null 2>/dev/null";

my $bsize = 0;
if ($data_type eq "pos") {
	$file_type  = ".pos";
}
else {
	die "[lm_mergepos] Sorry buddy, data type \"$data_type\" not supported (yet)\n";
}


# Check folders etc
my $folder_src = "root/AG/Sweeps/lm_pos/";

print "[lm_mergepos] Data type is \"$file_type\", block size is $bsize bytes\n";
print "              Source folder: $folder_src\n";


die "[lm_mergepos] Error: SOURCE folder does not exist" unless -e $folder_src ;

my @pattern_ns = `find $folder_src | grep "_0.pos"`;
my @pattern    = sort {$a cmp $b} @pattern_ns;

foreach my $pat (@pattern) {
	print "$pat\n";
}
