#!/bin/bash
# Copyright (C) 2007 Michele Tavella <michele@liralab.it>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

# LTC_S1
# lmtools2 toolchain: step 1
# Creates $US/WAV file in order to hand-detect
# AG500 sequences.
# Sequences do need to be written in $SEQS_TXT

PATH_ROOT="root"
if [ -e $PATH_ROOT ]; then
	echo "File $PATH_ROOT (symlink) exists"
	
	# Export US PCM stream
	DV_US="root/US/stream.dv"
	WA_US="cache/us_track.wav"
	if [ -e $WA_US ]; then
		echo "File $WA_US exists"
	else
		echo "File $WA_US does not exist"
		ffmpeg -i $DV_US $WA_US
	fi

	# Export CC PCM stream
	DV_CC="root/CC/stream.dv"
	WA_CC="cache/cc_track.wav"
	if [ -e $WA_CC ]; then
		echo "File $WA_CC exists"
	else
		echo "File $WA_CC does not exist"
		ffmpeg -i $DV_CC $WA_CC
	fi

	# Create configuration file for lm_collect
	CFG_CD="config/lm_collect.cfg"
	if [ -e $CFG_CD ]; then
		echo "File $CFG_CD exists"
	else
		echo "File $CFG_CD does not exist: creating empty pattern"
		for idx in `seq 0 8`; do
			echo "$idx/" >> $CFG_CD
		done
	fi
else
	echo "File $PATH_ROOT (symlink) does not exist. Please create it!"
fi
