#!/usr/bin/perl
# LTC_S2
# lmtools2 toolchain: step 2
# Creates config/sequence_XXXX.txt files used 
# in LTC_S3 to perform per-sequence word 
# segmentation.

use Getopt::Long;
use File::Copy;
use Cwd;
use Term::ANSIColor;
use Sys::Hostname;


sub mImportFile
{
	my $file = $_[0];
	
	open(FID, "< $file") or die "Error ($file): $!\n";
	my @data = <FID>;
	close (FID);

	return @data;
}


$file_dv   = "root/US/stream.dv";
$file_seqs = "config/segments.txt";

my @seqs = mImportFile($file_seqs);

foreach $line (@seqs) {
	chomp($line);
    $line =~ /^(.*)(\/)(.*)(\/)(.*)$/;
	$txt  = $1;
	$t0   = $3;
	$t1   = $5;
	
	$txtf = sprintf("%.4d", $txt);
	print "Sequence $txt, ";
	print "t0 = $t0, ";
	print "t1 = $t1\n";
	$file_txt = "wd_" . $txtf . "_sequence" . ".dd";
	$file_log = "wd_" . $txtf . "_log"      . ".pd";
	$file_seg = "wd_" . $txtf . "_segment"  . ".wav";
	$file_seq = "wd_" . $txtf . "_sequence" . ".wav";
	
	$file_txtt = "config/$file_txt";
	$file_logt = "log/$file_log";
	$file_segt = "cache/$file_seg";
	$file_seqt = "cache/$file_seq";
	print "  Sequence  $file_txtt\n";	# pdetect words
	print "  Log:      $file_logt\n";	# pdetect std output
	print "  Segment:  $file_segt\n";
	print "  Sequence: $file_seqt\n";
	$cmd = "pdetect --stream $file_dv --t0 $t0 --t1 $t1 --log $file_txtt --seg $file_segt --seq $file_seqt 1> $file_logt";
	system($cmd);
}
