#!/usr/bin/perl
# Copyright (C) 2007 Michele Tavella <michele@liralab.it>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

use Getopt::Long;
use File::Copy;
use Cwd;
use Term::ANSIColor;
use Sys::Hostname;

sub mImportFile {
	my $file = $_[0];
	
	open(FID, "< $file") or die "Error ($file): $!\n";
	my @data = <FID>;
	close (FID);

	return @data;
}

# Look for SEQ folders
my $folders_regex = "seq_*";
my @folders_seq_ns = `find . -iname "$folders_regex"`;
my @folders_seq = sort {$a cmp $b} @folders_seq_ns;

# Few experiments (7,8,9) do have inveted segmentation peaks.
my @cfg_invert = mImportFile("config/lm_invert.cfg");
my $param_invert = @cfg_invert[0];
chomp($param_invert);
$param_invert = int($param_invert);

# Parse each SEQ folder
foreach $folder_seq (@folders_seq) {
	# Nuke the carrier return char
	chomp($folder_seq);
	
	# Extract SEQ folder number
	$folder_seq =~ /^(.*)(_)(.*)$/;
	my $idx_seq = $3;
	my $t_idx_seq = int($idx_seq);

	# Look for US-DV files
	my $us_regex = "wd_*_us.dv";
	my @us_files_ns = `find $folder_seq/ -iname "$us_regex" | grep -v "ag"`;
	my @us_files = sort {$a cmp $b} @us_files_ns;
	
	my $words =	@us_files;
	print "Sequence $idx_seq: total $words\n";
	
	#system("matlab -nosplash -nojvm -r \"lmpkgAlignProxy($idx_seq, 0, $words)\" ");
	for ($word = 0; $word < $words; $word = $word + 1)
	{
		my $file_data = sprintf('seq_%.4d/wd_%.4d.mat', $idx_seq, $word);
		if (-e $file_data) {
			print "File $file_data exists... Skipping packaging operations\n";
		}
		else {
			print "File $file_data needs to be created\n";
			system("matlab -nosplash -nojvm -r \"lmpkgAlignProxy($idx_seq, $word, \'$file_data\', $param_invert);\" ");
		}
	}
}
