#!/usr/bin/perl
# Copyright (C) 2007 Michele Tavella <michele@liralab.it>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

use Getopt::Long;
use File::Copy;
use Cwd;
use Term::ANSIColor;
use Sys::Hostname;
use strict;

sub mImportFile {
	my $file = $_[0];
	
	open(FID, "< $file") or die "Error ($file): $!\n";
	my @data = <FID>;
	close (FID);

	return @data;
}

# Look for SEQ folders
my $folders_dist_rx = "dist_*";
my @folders_dist_ns = `find . -iname "$folders_dist_rx"`;
my @folders_dist = sort {$a cmp $b} @folders_dist_ns;


foreach my $folder_dist (@folders_dist) {
	chomp($folder_dist);
	print "[lm_repack] Working folder: $folder_dist\n";

	my $cmd_matlab = "matlab -nosplash -nojvm -r \"lmpkgRepackProxy(\'$folder_dist\');\"";
	system($cmd_matlab);	
}
