#!/bin/bash
# Copyright (C) 2007 Michele Tavella <michele@liralab.it>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

CURRENT_PATH=`pwd`
echo "Current path: $CURRENT_PATH";

if [ "`pwd | grep lmtools2`" == "$CURRENT_PATH" ]; then
	if [ "`pwd | grep scripts`" == "$CURRENT_PATH" ]; then
		echo "     Warning: Script executed inside the lmtools2/script folder"
		cd ../
		CURRENT_PATH=`pwd`
		echo "Correct path: $CURRENT_PATH"
	fi

	echo -e '\nAre you sure this is correct (Yes/no)? \c'
    read USER_CHOICE;
	if [ "$USER_CHOICE" == "Yes" ]; then
		echo "Adding lmtools path to ~/.bashrc";
		echo "# lmtools2 path" >> ~/.bashrc;
		echo -e "export LMT2_ROOT=\"$CURRENT_PATH\"" >> ~/.bashrc;
		echo -e "export PATH=\"\$LMT2_ROOT/bin:\$LMT2_ROOT/scripts:\${PATH}\"" >> ~/.bashrc;
	fi
fi
