#!/bin/bash
# Copyright (C) 2007 Michele Tavella <michele@liralab.it>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

if [ "$USERNAME" == "michele" ]; then
	/usr/bin/vncserver :2 -geometry 1270x700
	/usr/bin/vncserver :3 -geometry 1270x700
	/usr/bin/vncserver :4 -geometry 1270x700
	/usr/bin/vncserver :5 -geometry 1270x700
elif [ "$USERNAME" == "gsalvi" ]; then
	/usr/bin/vncserver :12 -geometry 1270x700
	/usr/bin/vncserver :13 -geometry 1270x700
fi
