#!/bin/bash

all:
	@cd pdetect2; make all; make all -f Makefile.invert
	@cd walign2; make all; make all -f Makefile.invert

clean:
	@cd pdetect2; make clean; make clean -f Makefile.invert
	@cd walign2; make clean; make clean -f Makefile.invert
