#HOSTNAME=`hostname`
#USERNAME=`who`
#DATE=`date`

#CFLAGS += -Wall -g
CFLAGS += -Wall -march=pentium-m -O3 -pipe -fomit-frame-pointer -ffast-math
#CFLAGS += -Wall -march=pentium4  -O3 -pipe -fomit-frame-pointer -ffast-math
