#-------------------
# Makefile Config.
#-------------------

MAIN = mprocessdv
LIBS =  -lm -lavformat -lavcodec -lz #`Magick++-config --ldflags --libs` 
CFLAGS = -I../../include/ 

include ../../config/Makefile.cflags
include ../../config/Makefile.in
