#!/usr/bin/perl
# Copyright (C) 2007 Michele Tavella <michele@liralab.it>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

use Getopt::Long;
use File::Copy;
use Cwd;
use Term::ANSIColor;
use Sys::Hostname;
use POSIX qw(ceil floor);
use strict;

my $exp = shift;
 
if ($exp eq "") {
	die "num needed...";
}


# This is gonna be the worst script ever...
my @files_ns = `find . -follow | grep \"lm_rawpos\" | grep ini`;
my @files = sort {$a cmp $b} @files_ns;

my $win_cmd_1 = "C:\\AG500\\npsub\.exe path=\"C:\\lm\_data\\NUM\\lm\_rawpos\" sweepfile=FILE chantype=------------ job=refpat";
my $win_cmd_2 = "C:\\AG500\\npsub\.exe path=\"C:\\lm\_data\\NUM\\lm\_rawpos\" sweepfile=FILE job=norm";

print "$win_cmd_1\n";
print "$win_cmd_2\n";

foreach my $file (@files) {
	$file =~ s/\.\/root\/AG\/Sweeps\/lm_rawpos\///g; 
	$file =~ s/\.ini//g;
	chomp($file);

	my $cmd1 = $win_cmd_1;
	my $cmd2 = $win_cmd_2;
	
	$cmd1 =~ s/NUM/$exp/g;
	$cmd1 =~ s/FILE/$file/g;
	
	$cmd2 =~ s/NUM/$exp/g;
	$cmd2 =~ s/FILE/$file/g;
	
	#print "$file\n";
	print "$cmd1\n";
	print "$cmd2\n";
}
