#!/usr/bin/perl
# Copyright (C) 2007 Michele Tavella <michele@liralab.it>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

use Getopt::Long;
use File::Copy;
use Cwd;
use Term::ANSIColor;
use Sys::Hostname;
use POSIX qw(ceil floor);
use strict;

sub mImportFile {
	my $file = $_[0];
	
	open(FID, "< $file") or die "Error ($file): $!\n";
	my @data = <FID>;
	close (FID);

	return @data;
}

my $dir_exp = shift;
my $dir_trg = shift;
die "Usage: lm_makemovie /path/to/exp_0001 /path/to/movies\n" unless $dir_trg ne "";

my @usdv_files_ns  = `find $dir_exp -name "*_us.dv" | grep aln_`;
my @usdv_files     = sort {$a cmp $b} @usdv_files_ns;

for my $usdv_file (@usdv_files) {
	chomp($usdv_file);
	my $ccdv_file = $usdv_file;
	my $uswav_file = $usdv_file;
	my $agpos_file = $usdv_file;
	my $wdtxt_file = $usdv_file;

	$ccdv_file =~ s/us/cc/g;
	$uswav_file =~ s/dv/wav/g;
	$agpos_file =~ s/us/ag/g;
	$agpos_file =~ s/dv/pos/g;
	$wdtxt_file =~ s/_us//g;
	$wdtxt_file =~ s/dv/txt/g;

	system("./lm_make_1movie $usdv_file $ccdv_file $uswav_file $agpos_file $wdtxt_file $dir_trg");
}
