EXP_BASE="/home/michele/ContactCache/exp_"
MVI_DIR="/home/michele/ContactCache/Distribute/"

all:

exp1:
	./lm_make_1movie $(EXP_BASE)0001/ $(MVI_DIR)
exp2:
	./lm_make_1movie $(EXP_BASE)0002/ $(MVI_DIR)
exp3:
	./lm_make_1movie $(EXP_BASE)0003/ $(MVI_DIR)
exp4:
	./lm_make_1movie $(EXP_BASE)0004/ $(MVI_DIR)
exp5:
	./lm_make_1movie $(EXP_BASE)0005/ $(MVI_DIR)
exp6:
	./lm_make_1movie $(EXP_BASE)0006/ $(MVI_DIR)
exp8:
	./lm_make_1movie $(EXP_BASE)0008/ $(MVI_DIR)
exp9:
	./lm_make_1movie $(EXP_BASE)0009/ $(MVI_DIR)
test:
	./run_test.sh
